### ISSUE TITLE
fwcloud-websrv throw new ERR_HTTP_HEADERS_SENT('set');

### ISSUE THREAD

**Issue by prowebuk** [soltecsis/fwcloud-websrv#57]
Firstly, thanks for a generously sharing a great piece of software.

I have a slight issue with fwcloud-websrv quitting for no apparent reason, twice within the last 24 hours so thought I'd raise this issue.

I'm running 1.2.2 on Debian Bullseye 11.7 behind an NGINX TLS proxy with the following settings:

location / {
                proxy_pass https://xxx.xxx.xxx.xxx:3030/;
                proxy_set_header Origin https://xxx.xxx.xxx.xxx:3030;
                proxy_intercept_errors on;
                error_page 404 = /;
}

syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]: node:_http_outgoing:644
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     throw new ERR_HTTP_HEADERS_SENT('set');
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     ^
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     at new NodeError (node:internal/errors:387:5)
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     at ServerResponse.setHeader (node:_http_outgoing:644:11)
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     at ServerResponse.writeHead (node:_http_server:348:21)
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     at ProxyServer.<anonymous> (/opt/fwcloud/websrv/dist/src/websrv/websrv.service.js:75:25)
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     at ProxyServer.emit (/opt/fwcloud/websrv/node_modules/eventemitter3/index.js:210:27)
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     at ClientRequest.proxyError (/opt/fwcloud/websrv/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:165:18)
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     at ClientRequest.emit (node:events:513:28)
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     at TLSSocket.socketErrorListener (node:_http_client:494:9)
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     at TLSSocket.emit (node:events:513:28)
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:     at emitErrorNT (node:internal/streams/destroy:157:8) {
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]:   code: 'ERR_HTTP_HEADERS_SENT'
syslog:May 29 14:22:54 pw-fwcloud-1 fwcloud-websrv[984]: }
syslog:May 29 14:22:54 pw-fwcloud-1 systemd[1]: fwcloud-websrv.service: Main process exited, code=exited, status=1/FAILURE
syslog:May 29 14:22:54 pw-fwcloud-1 systemd[1]: fwcloud-websrv.service: Failed with result 'exit-code'.
syslog:May 29 14:22:54 pw-fwcloud-1 systemd[1]: fwcloud-websrv.service: Consumed 8min 28.540s CPU time.
syslog:May 29 15:16:47 pw-fwcloud-1 fwcloud-api[960]: [session-file-store] Deleting expired sessions

Many thanks

**Comment by cmunyoz** [comment]
Hi, thank you very much for use FWCloud.

Please, can you inform me about the releases of FWCloud-API, FWCloud-Websrv, FWCloud-Updater and FWCloud-UI?

Which of the three available methods (FWCloud-Script, Docker images or DEB/RPM packages) have you followed for install your FWCloud platform?

Best regards.

**Comment by prowebuk** [comment]
It's a great piece of software and a pleasure to use.

FWCloud-Websrv - v1.2.2
FWCloud-UI - v1.9.0
FWCloud-API - v1.9.1
FWCloud-Updater - v1.1.0

FWCloud-Script installer

Kind regards

Richard

**Comment by cmunyoz** [comment]
Thank you very much for your comments about FWCloud, I'm very glad to ear it! :-)

You have all the modules updated to the latest releases, thats fine.

Why are you using Nginx as a TLS proxy servers instead of accessing directly to FWCloud-Websrv for access the FWCloud-UI ?

If you communicate directly with FWCloud-websrv, do you have the same problem?

**Comment by prowebuk** [comment]
Re: Why are you using Nginx as a TLS 

I wanted to change the port to 443 and use my own certificates so changed the port and certificates in /opt/fwcloud/websrv/config/websrv.ts but the port didn't change although the certificates did and couldn't find any info in the documentation so used nginx as a quick fix

Re: If you communicate directly with FWCloud-websrv, do you have the same problem?

Once the webserver crashes, you can't get to  https://xxx.xxx.xxx.xxx:3030/ directly.

**Comment by cmunyoz** [comment]
In order to change the configuration of the FWCloud-Websrv process you have to modify the `/opt/fwcloud/websrv/.env` file.
For example, for change the listening port you have to add the next to such file:
`LISTEN_PORT=443`

You can change the path for the certificate and key files with the `HTTPS_CERT` and `HTTPS_KEY` but make sure that the files are accesible by the `fwcloud` user.

Please, can you make these changes, stop your Nginx server, restart the `fwcloud-websrv` service and access your FWCloud installation and make tests to verify if the problem arises again?
